"""initial schema

Revision ID: cb20e831a188
Revises: 
Create Date: 2026-09-15 11:42:49.271388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb20e831a188'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('old_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_activation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_change', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_revision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_version', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_deactivation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('number_of_revision', sa.Integer(), nullable=True),
    sa.Column('list_of_replaced_properties', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('list_of_replacing_properties', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('reason_for_rejection', sa.String(), nullable=True),
    sa.Column('relation_to_other_catalogues', sa.String(), nullable=True),
    sa.Column('language_of_creator', sa.String(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_properties', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('groups', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('symbols', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('used_in_countries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('subdivision_of_usage', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('physical_quantity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('measurement_method', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('dynamic', sa.Boolean(), nullable=False),
    sa.Column('dynamic_parameter', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('units', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('name_of_defining_values', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('defining_values', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tolerance', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('digital_format', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('textformat', sa.String(), nullable=True),
    sa.Column('possible_values', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('limit_values', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.create_table('propertyGroups',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_activation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_change', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_revision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_version', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_deactivation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('number_of_revision', sa.Integer(), nullable=True),
    sa.Column('list_of_replaced_property_groups', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('list_of_replacing_property_groups', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('reason_for_rejection', sa.String(), nullable=True),
    sa.Column('relation_to_other_catalogues', sa.String(), nullable=True),
    sa.Column('language_of_creator', sa.String(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('used_in_countries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('subdivision_of_usage', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('ALTERNATIVE_USAGE', 'CLASS', 'COMPOSITE_PROPERTY', 'DOMAIN', 'REFERENCE_DOCUMENT', name='propertygroupcategory'), nullable=False),
    sa.Column('groups', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_index(op.f('ix_propertyGroups_name'), 'propertyGroups', ['name'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('FILE_FORMAT', 'DATA_STANDARD', 'EUROPEAN_GUIDELINE', 'EUROPEAN_REGULATION', 'EUROPEAN_STANDARD', 'GUIDELINE', 'INTERNATIONAL_GUIDELINE', 'INTERNATIONAL_STANDARD', 'NATIONAL_GUIDELINE', 'NATIONAL_LAW', 'NATIONAL_STANDARD', 'ONTOLOGY', 'SPECIALIST_BOOK', 'TECHNICAL_REPORT', 'TECHNICAL_STANDARD', 'WORKING_GROUP', name='standardcategory'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subTitle', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('reference_URL', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_id'), 'standards', ['id'], unique=False)
    op.create_index(op.f('ix_standards_number'), 'standards', ['number'], unique=False)
    op.create_table('useCases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('relation_to_other_useCases', sa.String(), nullable=True),
    sa.Column('uc_owner_institution', sa.String(), nullable=True),
    sa.Column('uc_owner', sa.String(), nullable=True),
    sa.Column('conx_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useCases_id'), 'useCases', ['id'], unique=False)
    op.create_index(op.f('ix_useCases_name'), 'useCases', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('subUseCases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('conx_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('useCase_id', sa.Integer(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('inputs', sa.String(), nullable=True),
    sa.Column('outputs', sa.String(), nullable=True),
    sa.Column('potential_risks', sa.String(), nullable=True),
    sa.Column('distinction_from_other_sucs', sa.String(), nullable=True),
    sa.Column('dependency_of_other_sucs', sa.String(), nullable=True),
    sa.Column('assumptions', sa.String(), nullable=True),
    sa.Column('bpmn_png_url', sa.String(), nullable=True),
    sa.Column('bpmn_xml', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['useCase_id'], ['useCases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subUseCases_id'), 'subUseCases', ['id'], unique=False)
    op.create_index(op.f('ix_subUseCases_name'), 'subUseCases', ['name'], unique=False)
    op.create_index(op.f('ix_subUseCases_short_name'), 'subUseCases', ['short_name'], unique=False)
    op.create_table('useCase_standards',
    sa.Column('useCase_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.ForeignKeyConstraint(['useCase_id'], ['useCases.id'], ),
    sa.PrimaryKeyConstraint('useCase_id', 'standard_id')
    )
    op.create_table('subUseCase_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subUseCase_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('monetary_benefit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subUseCase_id'], ['subUseCases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subUseCase_roles_id'), 'subUseCase_roles', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subUseCase_id', sa.Integer(), nullable=True),
    sa.Column('roleOut_id', sa.Integer(), nullable=True),
    sa.Column('roleIn_id', sa.Integer(), nullable=True),
    sa.Column('usesDataspace', sa.Boolean(), nullable=True),
    sa.Column('related_class_id', sa.String(), nullable=True),
    sa.Column('data_carrier', sa.String(), nullable=True),
    sa.Column('dataformat_available', sa.String(), nullable=True),
    sa.Column('dataformat', sa.String(), nullable=True),
    sa.Column('timing', sa.String(), nullable=True),
    sa.Column('policies', sa.String(), nullable=True),
    sa.Column('data_size', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['roleIn_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['roleOut_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['subUseCase_id'], ['subUseCases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('useCase_roles',
    sa.Column('useCase_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['useCase_id'], ['useCases.id'], ),
    sa.PrimaryKeyConstraint('useCase_id', 'role_id')
    )
    op.create_table('transaction_properties',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('property_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['property_uuid'], ['properties.UUID'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'property_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_properties')
    op.drop_table('useCase_roles')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subUseCase_roles_id'), table_name='subUseCase_roles')
    op.drop_table('subUseCase_roles')
    op.drop_table('useCase_standards')
    op.drop_index(op.f('ix_subUseCases_short_name'), table_name='subUseCases')
    op.drop_index(op.f('ix_subUseCases_name'), table_name='subUseCases')
    op.drop_index(op.f('ix_subUseCases_id'), table_name='subUseCases')
    op.drop_table('subUseCases')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_useCases_name'), table_name='useCases')
    op.drop_index(op.f('ix_useCases_id'), table_name='useCases')
    op.drop_table('useCases')
    op.drop_index(op.f('ix_standards_number'), table_name='standards')
    op.drop_index(op.f('ix_standards_id'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_propertyGroups_name'), table_name='propertyGroups')
    op.drop_table('propertyGroups')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
