backend:
  image:
    repository: ghcr.io/project-construct-x/knowledge-hub-backend
    tag: latest
  storage:
    className: premium-perf1-stackit
    size: 30Gi

frontend:
  image:
    repository: ghcr.io/project-construct-x/knowledge-hub-frontend
    tag: latest

ingress:
  host: knowledge-hub.example.com
  className: nginx
  clusterIssuer: letsencrypt-prod

db:
  user: "user"
  password: "password"
  db: "appdb"
  storage:
    className: premium-perf1-stackit
    size: 30Gi
