appEnv: staging
logLevel: INFO

backend:
  image:
    repository: ghcr.io/project-construct-x/knowledge-hub-backend
    tag: latest
  storage:
    size: 30Gi

frontend:
  image:
    repository: ghcr.io/project-construct-x/knowledge-hub-frontend
    tag: latest

ingress:
  host: knowledge-hub.staging.construct-x.net

keycloak:
  url: https://centralidp.staging.construct-x.net/auth
  realm: knowledge-hub
  clientId: knowledge-hub

db:
  user: "user"
  db: "appdb_knowledge_hub_staging"
  storage:
    size: 30Gi
